"""add description column to roles table

Revision ID: add_description_to_roles
Revises: add_permissions_tables
Create Date: 2026-04-22 22:30:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "add_description_to_roles"
down_revision = "add_permissions_tables"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roles") as batch_op:
        batch_op.add_column(
            sa.Column("description", sa.String(length=255), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roles") as batch_op:
        batch_op.drop_column("description")
    # ### end Alembic commands ###
